title: Eunkyu Seong's Homepage
page-top-title: Eunkyu Seong 
top-section-bg-text: Applied Econometrics
home-subtitle: Eunkyu Seong (성은규)
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
